### PR TITLE
I believe that I have check in all the changes I made for my modification to this fork.

### PR DESCRIPTION
**Pull request by StyroCupMan**
This version of Notpod supports selecting multiple playlists with each playlist's songs being put into a separate folder on the destination drive

### CODE REVIEW

**Comment by jaranflaath** [comment]
Hi, I think you may have forgotten to commit something - the changes to the configuration form itself. I get several compilation errors complaining about a missing "clbAssocPlaylist".

**Comment by StyroCupMan** [comment]
OK, I think I got the missing file. I added it to my previous commit.
Hopefully that works.

Thanks,
Aaron

On Sun, Jan 15, 2012 at 2:00 AM, Jaran Nilsen <
reply@reply.github.com

**Comment by jaranflaath** [comment]
Hi Aaron, apologies for taking so long before getting back to you. I've looked at the last commit and it's now building fine. Like your suggestions and I will look at getting them merged, but there's some changes that I want to do to before it can go into the master branch. If you want to do more work on this, I will obviously appreciate any assistance, if not I will look at it myself when there's time. Here's my list of immediate changes: 
1. Using a pipe (|) to separate playlists names is fine and ensures backwards compatibility with existing configuration, however, we need to make sure that playlist names containing the pipe character does not break this configuration format.
2. The layout of the preferences dialog is now a little crowded. Need to look at ways to make this look better (no immediate concern before a merge, but important none the less)
3. Ensure the StandardSynchronizer does not maintain duplicate entries when copying new files, in cases where multiple playlists references the same tracks.

**Comment by jaranflaath** [comment]
I've pulled this merge request into the following branch: https://github.com/notpod/Notpod-1.x/tree/multiplaylist

If you want to continue contributing, feel free to open another pull request :)

**Pull request closed without merging**
